### ISSUE TITLE
I would like to add the ability to force MFA for users on admin accounts.

### ISSUE THREAD

**Issue by junius06** [DefGuard/defguard#620] opened 2024-04-15 05:43 UTC
I would like to add the ability to force MFA for users on admin accounts.

Now, users enable MFA themselves.
But Users can remove MFA and we don't want users to be able to delete it.

It would be nice to be able to set it so that disabling the MFA function in a specified location is the admin's unique privilege.

**Comment by teon** [comment] 2024-08-15 14:30
Closing -as duplicate of: https://github.com/DefGuard/defguard/issues/417

**Closed by teon** 2024-08-15 14:30 UTC
Labels: feature
