### ISSUE TITLE
Django integration issue

### ISSUE THREAD

**Issue by andrzejpiasecki** [DefGuard/defguard#356] opened 2023-10-04 09:10 UTC
**Describe the bug**
Obtaining token with method:
```oauth.defguard.authorize_access_token(request)```
failed with an exception:
```
iaas-djangoserver-1  | INFO 2023-10-04 07:25:23,091 basehttp 315 140638401312448 "GET /oauth/defguard-login/ HTTP/1.1" 302 0
iaas-djangoserver-1  | INFO 2023-10-04 07:25:23,457 basehttp 315 140638401312448 "GET /oauth/redirect?error=access_denied&state=XttZHHERXW0HIv7vEG74ZvUQHMThis HTTP/1.1" 301 0
iaas-djangoserver-1  | ERROR 2023-10-04 07:25:23,722 log 315 140638401312448 Internal Server Error: /oauth/redirect/
iaas-djangoserver-1  | Traceback (most recent call last):
iaas-djangoserver-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
iaas-djangoserver-1  |     response = get_response(request)
iaas-djangoserver-1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
iaas-djangoserver-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
iaas-djangoserver-1  |   File "/server/django/oauth/views.py", line 43, in defguard_authorize
iaas-djangoserver-1  |     token = oauth.defguard.authorize_access_token(request)
iaas-djangoserver-1  |   File "/usr/local/lib/python3.8/site-packages/authlib/integrations/django_client/apps.py", line 67, in authorize_access_token
iaas-djangoserver-1  |     raise OAuthError(error=error, description=description)
iaas-djangoserver-1  | authlib.integrations.base_client.errors.OAuthError: access_denied: 
iaas-djangoserver-1  | ERROR 2023-10-04 07:25:23,724 basehttp 315 140638401312448 "GET /oauth/redirect/?error=access_denied&state=XttZHHERXW0HIv7vEG74ZvUQHMThis HTTP/1.1" 500 145
```
when http is used instead of https and defguard receives GET instead of POST

**To Reproduce**
Add defguard integration to Django application based on https://defguard.gitbook.io/defguard/features/openid-connect/django-rest-react-app#django-setup
Specify http instead of https links in configuration:
```
defguard = oauth.register(
    name="defguard",
    client_id=os.getenv("DEFGUARD_CLIENT_ID", "DEFGUARD_CLIENT_ID"),
    client_secret=os.getenv("DEFGUARD_CLIENT_SECRET", "DEFGUARD_CLIENT_SECRET"),
    access_token_url=os.getenv("DEFGUARD_ACCESS_TOKEN_URL", "https://defguard.teonite.net/api/v1/oauth/token"),
    access_token_params=None,
    authorize_url=os.getenv("DEFGUARD_AUTHORIZE_URL", "https://defguard.teonite.net/api/v1/oauth/authorize"),
    api_base_url=os.getenv("DEFGUARD_API_BASE_URL", "https://defguard.teonite.net/api/v1/oauth/userinfo"),
    client_kwargs={"scope": os.getenv("DEFGUARD_SCOPE", "openid email profile")},
    server_metadata_url=os.getenv("DEFGUARD_METADATA_URL",
                                  "https://defguard.teonite.net/.well-known/openid-configuration"),
)
```

**Expected behavior**
Login with defguard should work properly.

**Additional context**
Problem lies probably in our local network environment where haproxy redirects requests from http to https and changes POST to GET.

**Comment by moubctez** [comment] 2023-10-04 09:13
https://stackoverflow.com/questions/12548341/how-to-work-around-post-being-changed-to-get-on-302-redirect

**Comment by filipslezaklab** [comment] 2023-10-19 12:17
I've tested the whole setup on HTTP with localhost domain on both Defguard and Django, the issue did not arise.

As this issue is not caused by Defguard itself we will close it for the time being.

**Closed by filipslezaklab** 2023-10-19 12:17 UTC
Labels: bug
