### ISSUE TITLE
Make SMTP credentials optional

### ISSUE THREAD

**Issue by dbutti** [DefGuard/defguard#623] opened 2024-04-16 16:21 UTC
**Is your feature request related to a problem? Please describe.**
When entering SMTP credentials for Defguard core under "Settings" in the web interface, username and password are compulsory. They should be optional instead, in order to make it possible to use an open SMTP relay.

**Describe the solution you'd like**
SMTP authentication should be optional

**Describe alternatives you've considered**
With the current version, only SMTP relays requiring authentication can be used.

**Comment by drag0n141** [comment] 2024-11-15 13:10
+1 for that, because of that i can not use the smtp setting.

**Comment by honzaka** [comment] 2024-11-18 15:08
+1 for that

**Comment by teon** [comment] 2024-11-22 11:17
Fixed in https://github.com/DefGuard/defguard/pull/869 - today should be 1.1.2 release.

**Comment by teon** [comment] 2024-11-22 18:16
@dbutti @drag0n141 @honzaka 1.1.2 released - please confirm that SMTP works for you.

**Closed by teon** 2024-11-22 18:16 UTC
Labels: feature, good first issue, help wanted

**Comment by drag0n141** [comment] 2024-11-23 14:49
I can not test at the moment, because of the missing userspace in docker support.

**Comment by honzaka** [comment] 2024-11-23 20:55
I will test it on monday (standalone package based installation).

**Comment by honzaka** [comment] 2024-11-25 06:29
I can confirm, that SMTP now works without credentials. Thank you!

**Comment by Vaarlion** [comment] 2024-11-25 14:25
same here, thank's !
