### ISSUE TITLE
Feature Request: Support for Azure AD / Entra ID

### ISSUE THREAD

**Issue by syphernl** [DefGuard/defguard#582] opened 2024-03-13 11:04 UTC
**Is your feature request related to a problem? Please describe.**

We manage our users in Azure AD / Entra ID. It would be nice if we could allow users to login to DefGuard using their Microsoft account. 
As an administrator it would be desirable to be able to assign a particular group that is allowed to login to Defguard.

**Describe the solution you'd like**

Integration with Azure AD / Entra ID via SAML and/or OpenID.

**Comment by teon** [comment] 2024-07-08 11:09
Duplicate of currently in progress #602

**Closed by teon** 2024-07-08 11:09 UTC
Labels: feature, enterprise
